<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Testcontainers.MsSql" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\TaskManagerBackend.Application\TaskManagerBackend.Application.csproj" />
      <ProjectReference Include="..\..\..\src\TaskManagerBackend.DataAccess\TaskManagerBackend.DataAccess.csproj" />
      <ProjectReference Include="..\..\TaskManagerBackend.Tests.Common\TaskManagerBackend.Tests.Common.csproj" />
    </ItemGroup>

</Project>