# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: TaskManagerBackend
    - name: Build
      run: dotnet build --no-restore
      working-directory: TaskManagerBackend
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal --filter "Category=Unit"
      working-directory: TaskManagerBackend
    - name: Run integration tests
      run: dotnet test --no-build --verbosity normal --filter "Category=Integration"
      working-directory: TaskManagerBackend